### ISSUE TITLE
With netbox-kafka-producer Installed netbox is blocking on a change

### ISSUE THREAD

**Issue by madeinoz67** [ebusto/netbox-kafka-producer#1]
When testing this out I'm seeing blocking behaviour on netbox when the settings are installed and configured to my single node kafka instance, i.e. when I update something in net box it will hang and requires a restart

Is there any way to enable logging to try and debug?

my kafka nodes are on port 9094 so I'm assuming that this is appended to the server in the settings e.g. xxx.xxx.xxx.xxx:9094 ?

My kafka instance is working on a simple producer / consumer is there anything else required on the kafka side of things?  Currently I have auto-create topics while I'm evaluating

**Comment by ebusto** [comment]
This definitely sounds like the Kafka producer blocking when trying to publish the message, which I've encountered before (in a different application) when the Kafka cluster was unhealthy.

The `SERVERS` configuration value is passed directly as [bootstrap.servers](https://docs.confluent.io/current/installation/configuration/producer-configs.html), which supports specifying a non-standard port, so that shouldn't be the problem.

It looks like the Confluent Kafka library supports a hook for logging, which currently isn't utilized by `netbox-kafka-producer`.

Unfortunately I'm heading out on vacation for the next couple of weeks. If this problem still persists and isn't just a cranky Kafka cluster, I'll help investigate when I get back. Having some logging and debug functionality is a good idea.

**Comment by madeinoz67** [comment]
Enjoy your holiday :).   

I'll poke around a bit more to play with it.  This is a new Kafka Cluster running on Kubernetes using the Strimzi operator so may be something to do with how the LoadBalancer (MetalLB) is exposing the kafka services.   Currently it's exposing the bootstrap and nodes on 9094 on individual IPs for the bootstrap and the kafka nodes which when testing with KafkaCat is testing successfully using the bootstrap addresses both as producers and consumers just fine.

**Comment by ebusto** [comment]
Alright, I'm slowly catching up on life.

We discovered that if the `SERVERS` value in the `KAFKA` setting was something weird, like an empty string, then the middleware can hang trying to publish the change.

Can you share the relevant section of your `settings.py`?

I created an issue in our internal repo to validate settings to catch little things like this.
